window.help_translations = {
    help: {
        tools: {
            pen: "Pen Tool Guide:\n1. Pen Types: Choose from Normal, Pencil (grainy), Ballpoint (pressure), Fountain (calligraphy), or Brush (ink).\n2. Color: 8 presets available. Click the plus icon for a custom color picker.\n3. Size: Adjust stroke width (1-50px) using the slider.\n4. Tip: Hold Shift key to draw straight lines.",
            shape: "Shape Tool Guide:\n1. Shapes: Line, Rectangle, Circle, Ellipse, Arrow, Double Arrow.\n2. How to Draw: Press and drag, then release to finish.\n3. Arrow Size: Adjust the arrow head size independently (limited to be at least the line thickness).\n4. Style: Shapes use the current pen color and thickness settings.",
            eraser: "Eraser Tool Guide:\n1. Shape: Choose between Circle or Square eraser.\n2. Size: Adjust eraser size using the slider.\n3. Clear All: Use the 'Clear' button on the toolbar to clear the entire canvas.",
            select: "Selection Tool Guide:\n1. Click mode: Tap an existing stroke or object to select it.\n2. Box Select: Drag a rectangle to select everything inside.\n3. Lasso: Draw a freehand loop for irregular selections.\n4. Tip: After selecting, use the on-canvas handles or toolbar actions to edit, copy, or delete.",
            lineStyle: "Line Style Guide:\n1. Styles: Switch between solid, dashed, dotted, wavy, and multi-line.\n2. Density: Dashed, dotted, and wavy styles can be fine-tuned with dedicated sliders.\n3. Multi-line: Adjust both line count and spacing for parallel strokes.\n4. Preview: Check the sample area before applying so pen and shape output stay consistent."
        },
        settings: "Settings Guide:\n1. Tabs: General, Display, Canvas, Background, About, Announcement, and More are grouped by task.\n2. Live Preview: Most options apply immediately, so you can fine-tune the interface while using the board.\n3. Language: Switching language updates the UI and help text without reloading.\n4. Tip: If a panel feels crowded, use the tab sidebar first, then adjust only the section you need.",
        background: "Background Settings Guide:\n1. Color: Choose canvas background color.\n2. Patterns: Grids, Lines, Music Staff, Coordinate System, etc.\n3. Image: Upload a local image as background. Supports move, resize, rotate, and flip.\n4. Coordinates: When Coordinate pattern is selected, click 'Move Origin' to drag the origin point on the canvas.",
        features: {
            shape: "**Shape Tool in More Features**:\n1. Tap to switch to shape drawing mode.\n2. Uses current stroke color and line width.\n3. Supports line, rectangle, circle, ellipse, arrow and double-arrow.",
            timer: "Timer Guide:\n1. Modes: Stopwatch and Countdown.\n2. Setting Time: Input hours, minutes, and seconds for countdown.\n3. Sound: Enable completion sound. Supports custom audio upload.\n4. Loop: Set loop count for the sound.\n5. Fullscreen: View timer in fullscreen mode.\n6. Minimal Mode: Double-click the time display to toggle minimal view.",
            randomPicker: "Random Picker Guide:\n1. Import Names:\n   - Manual: Type names, one per line.\n   - Excel Import: Click 'Import' in settings, select an Excel/CSV file. Auto-reads 'Name' column (customizable).\n2. Modes: Pick by Name or Number.\n3. Repeat: Enable 'Allow Repeats' to allow picking the same name multiple times.",
            scoreboard: "Scoreboard Guide:\n1. Add Team: Click to add a new score column.\n2. Adjust Score: Click '+' or '-' buttons.\n3. Edit Name: Double-click team name to edit.\n4. Reset: Resets all scores to zero but keeps teams.",
            teachingTools: "Teaching Tools Guide:\n1. Tool Types: Ruler (2 styles) and Set Square (60° and 45° types).\n2. Add Tools: Set quantity in 'Add New' section and click 'Confirm' to add to canvas.\n3. Move Tools: Single-click and drag to move tool position.\n4. Adjust Tools: Double-click to show control points for rotate, resize, and delete.\n5. Edge Drawing: Drawing near tool edges will snap the stroke to the edge.\n6. Multiple Instances: You can place multiple tools on the canvas simultaneously.",
            timeDisplay: "Time Display Settings Guide:\n1. Display Options: Choose to show date, time, or both.\n2. Timezone: Supports major global timezones with DST auto-adjustment.\n3. Format: 12/24 hour time format, multiple date formats available.\n4. Style: Customize font color, background color, and opacity.\n5. Fullscreen Mode: Single-click or double-click to enter fullscreen time display.\n6. Drag to Move: The time display widget can be freely dragged to any position.",
            insertImage: "**Insert Image Guide**:\n1. Select an image from local files.\n2. Drag to move after insertion.\n3. Use handles to scale and rotate.\n4. Supports horizontal and vertical flip.",
            insertText: "Insert Text Guide:\n1. Input Text: Type text in the popup window (supports multiple lines).\n2. Style: Adjust font size and color below the input area.\n3. Position: After insertion, drag the text box to move it.\n4. Rotate & Scale: Drag the top handle to rotate, or corner handles to scale the text.\n5. Edit: Double-click the text on canvas to edit content and style again.\n6. Confirm: Click the checkmark button to stamp the text onto the canvas (becomes pixels, uneditable)."
        }
    },
    common: {
        help: "Help"
    }
};
