window.help_translations = {
    help: {
        tools: {
            pen: "[color=#0a63c9]**Pen Tool**[/color]\n- **Styles**: Normal, Pencil, Ballpoint, Fountain, and Brush.\n- **Color**: Use preset swatches or the custom color picker.\n- **Size**: Adjust stroke width from 1-50px.\n- **Tip**: Hold Shift to draw a straight line quickly.",
            shape: "[color=#0a63c9]**Shape Tool**[/color]\n- **Shapes**: Line, Rectangle, Circle, Ellipse, Arrow, and Double Arrow.\n- **Draw**: Press and drag, then release to finish.\n- **Arrow heads**: Arrow size can be adjusted independently.\n- **Style sync**: Shapes reuse the current pen color, size, and line style.",
            eraser: "[color=#0a63c9]**Eraser Tool**[/color]\n- **Shapes**: Circle and Square erasers are available.\n- **Erase rule**: The square eraser clears by its visible outer frame, so touching a stroke with the frame erases it.\n- **Size**: Adjust the eraser size with the slider.\n- **Tip**: Use the toolbar Clear button when you need to wipe the whole page.",
            select: "[color=#0a63c9]**Selection Tool**[/color]\n- **Tap Select**: Tap an existing stroke or object.\n- **Box Select**: Drag a rectangle over the target area.\n- **Lasso**: Draw a freehand loop for irregular selections.\n- **Actions**: Move, copy, delete, or refine the selected content afterward.",
            lineStyle: "[color=#0a63c9]**Line Style**[/color]\n- **Types**: Solid, Dashed, Dotted, Wavy, and Multi-line.\n- **Fine tuning**: Dashed, dotted, and wavy styles each have density controls.\n- **Multi-line**: Adjust both line count and spacing.\n- **Tip**: Check the preview before applying it."
        },
        settings: "[color=#0a63c9]**Settings Panel**[/color]\n- **Sections**: General, Display, Canvas, Background, About, Announcement, and More.\n- **Live update**: Most options apply immediately.\n- **Window controls**: When a modal supports resizing, drag its corners while holding. After resizing, you can use **Restore Size** and **Keep Centered**.\n- **Language**: Switching language refreshes the UI and help text together.",
        background: "[color=#0a63c9]**Background Settings**[/color]\n- **Color**: Choose preset or custom background colors.\n- **Teaching patterns**: Grid, four-line paper, music staff, coordinate plane, and more.\n- **Background image**: Local images support move, resize, rotate, and flip.\n- **Coordinates**: Click Move Origin, then press and drag to reposition the origin.",
        features: {
            shape: "[color=#0a63c9]**More > Shape**[/color]\n- Quickly switches to shape drawing mode.\n- Reuses the current line color, width, and style.\n- Great for entering shape mode from the More panel.",
            timer: "[color=#0a63c9]**Timer**[/color]\n- **Drag**: Press and hold the empty part of the title bar to move the widget; Help, Settings, and Close respond only inside their own buttons.\n- **Modes**: Stopwatch and Countdown.\n- **Time**: Countdown supports hours, minutes, and seconds.\n- **Alerts**: Completion sound, custom audio, and loop count are supported.\n- **Display**: Fullscreen mode is available; double-click the digits for minimal view.",
            randomPicker: "[color=#0a63c9]**Random Picker**[/color]\n- **Drag**: Press and hold the empty header area to move the widget.\n- **Names**: Type one name per line or import from Excel / CSV.\n- **Modes**: Pick by Name or Number.\n- **Repeats**: Allow Repeats lets the same result appear again.\n- **Tip**: The Help button now responds only on the actual question-mark button.",
            scoreboard: "[color=#0a63c9]**Scoreboard**[/color]\n- **Drag**: Press and hold the empty header area to move the widget.\n- **Teams**: Add, rename, or remove teams.\n- **Scores**: Use + and - to adjust points.\n- **Reset**: Reset clears scores without removing teams.\n- **Tip**: The Help button only reacts inside its own button area.",
            teachingTools: "[color=#0a63c9]**Teaching Tools**[/color]\n- **Types**: Rulers plus 45° and 60° set squares.\n- **Insert**: Set the quantity and confirm to place tools on the canvas.\n- **Move**: Press and drag the tool body.\n- **Adjust**: Use control handles to rotate, resize, or delete.\n- **Edge drawing**: Strokes snap when they approach a tool edge.",
            timeDisplay: "[color=#0a63c9]**Time Display**[/color]\n- **Panel drag**: Press and hold the empty panel area to move it.\n- **Content**: Show date, time, or both.\n- **Format**: Timezone, 12/24-hour mode, and multiple date formats are available.\n- **Style**: Customize text color, background color, and opacity.\n- **Display**: Fullscreen is supported, and the Help button responds only on the button itself.",
            insertImage: "[color=#0a63c9]**Insert Image**[/color]\n- Insert a local image onto the canvas.\n- Press and drag the image to move it.\n- Drag corner or edge handles to resize.\n- Use the top handle to rotate; horizontal and vertical flip are supported.",
            insertText: "[color=#0a63c9]**Insert Text**[/color]\n- **Input**: Multi-line text is supported.\n- **Style**: Adjust font size, color, and related options.\n- **Adjust**: Press and drag the text box to move it, drag corners to resize, and use the top handle to rotate.\n- **Edit**: Double-click inserted text to edit it again.\n- **Confirm**: The checkmark stamps the text onto the canvas."
        }
    },
    common: {
        help: "Help"
    }
};
