window.help_translations = {
    help: {
        tools: {
            pen: "Guía de la herramienta Pluma:\n1. Tipos de pluma: Normal, Lápiz (granulado), Bolígrafo (presión), Estilográfica (caligrafía) o Pincel (tinta).\n2. Color: 8 preajustes disponibles. Haga clic en el icono de más para un selector de color personalizado.\n3. Tamaño: Ajuste el ancho del trazo (1-50px) usando el control deslizante.\n4. Consejo: Mantenga pulsada la tecla Shift para dibujar líneas rectas.",
            shape: "Guía de la herramienta Forma:\n1. Formas: Línea, Rectángulo, Círculo, Elipse, Flecha, Flecha doble.\n2. Cómo dibujar: Presione y arrastre, luego suelte para terminar.\n3. Tamaño de flecha: Ajuste el tamaño de la punta de flecha independientemente (limitado a al menos el grosor de la línea).\n4. Estilo: Las formas usan la configuración actual de color y grosor de la pluma.",
            eraser: "Guía de la herramienta Borrador:\n1. Forma: Elija entre borrador circular o cuadrado.\n2. Tamaño: Ajuste el tamaño del borrador usando el control deslizante.\n3. Borrar todo: Use el botón 'Borrar' en la barra de herramientas para borrar todo el lienzo.",
            select: "Guía de la herramienta Selección:\n1. Modo clic: Toque un trazo u objeto existente para seleccionarlo.\n2. Selección por caja: Arrastre un rectángulo para seleccionar todo lo que quede dentro.\n3. Lazo: Dibuje un contorno libre para áreas irregulares.\n4. Consejo: Después de seleccionar, use los controles del lienzo o las acciones para mover, copiar o eliminar.",
            lineStyle: "Guía de estilo de línea:\n1. Estilos: Cambie entre línea sólida, discontinua, punteada, ondulada y multilínea.\n2. Densidad: Los estilos discontinuo, punteado y ondulado tienen controles propios.\n3. Multilínea: Ajuste por separado la cantidad de líneas y la distancia entre ellas.\n4. Vista previa: Revise la muestra antes de aplicar para mantener coherencia entre pluma y formas."
        },
        settings: "Guía de configuración:\n1. Pestañas: General, Pantalla, Lienzo, Fondo, Acerca de, Anuncios y Más están organizadas por tarea.\n2. Vista previa en vivo: La mayoría de opciones se aplican al instante para ajustar la interfaz mientras trabaja.\n3. Idioma: Al cambiar el idioma se actualizan la interfaz y la ayuda sin recargar.\n4. Consejo: Si ve demasiadas opciones, cambie primero a la pestaña adecuada y ajuste solo esa sección.",
        background: "Guía de configuración de fondo:\n1. Color: Elija el color de fondo del lienzo.\n2. Patrones: Cuadrículas, Líneas, Pentagrama, Sistema de coordenadas, etc.\n3. Imagen: Cargue una imagen local como fondo. Soporta mover, redimensionar, rotar y voltear.\n4. Coordenadas: Cuando se selecciona el patrón de Coordenadas, haga clic en 'Mover origen' para arrastrar el punto de origen en el lienzo.\n5. Dibujar puntos y línea: admite **Solo línea**, **Conexión automática** y **Conectar selección**. En el modo de selección, solo se unen los puntos seleccionados.\n6. Ayuda: tanto la ventana de coordenadas como la ventana flotante de dibujar puntos y línea tienen su propio botón de ayuda.",
        features: {
            shape: "**Herramienta Forma en Más funciones**:\n1. Pulse para cambiar al modo de dibujo de formas.\n2. Usa el color y grosor de línea actuales.\n3. Soporta línea, rectángulo, círculo, elipse, flecha y doble flecha.",
            timer: "Guía del Temporizador:\n1. Modos: Cronómetro y Cuenta regresiva.\n2. Configurar tiempo: Ingrese horas, minutos y segundos para la cuenta regresiva.\n3. Sonido: Habilite el sonido de finalización. Soporta carga de audio personalizado.\n4. Bucle: Establezca el número de repeticiones del sonido.\n5. Pantalla completa: Vea el temporizador en modo de pantalla completa.\n6. Modo mínimo: Haga doble clic en la visualización del tiempo para cambiar a vista mínima.",
            randomPicker: "Guía del Selector aleatorio:\n1. Importar nombres:\n   - Manual: Escriba nombres, uno por línea.\n   - Importar Excel: Haga clic en 'Importar' en la configuración, seleccione un archivo Excel/CSV. Lee automáticamente la columna 'Nombre' (personalizable).\n2. Modos: Seleccionar por Nombre o Número.\n3. Repetición: Habilite 'Permitir repeticiones' para permitir seleccionar el mismo nombre varias veces.",
            scoreboard: "Guía del Marcador:\n1. Agregar equipo: Haga clic para agregar una nueva columna de puntuación.\n2. Ajustar puntuación: Haga clic en los botones '+' o '-'.\n3. Editar nombre: Haga doble clic en el nombre del equipo para editar.\n4. Restablecer: Restablece todas las puntuaciones a cero pero mantiene los equipos.",
            teachingTools: "Guía de Herramientas didácticas:\n1. Tipos de herramientas: Regla (2 estilos) y Escuadra (tipos 60° y 45°).\n2. Agregar herramientas: Establezca la cantidad en la sección 'Agregar nuevo' y haga clic en 'Confirmar' para agregar al lienzo.\n3. Mover herramientas: Haga clic simple y arrastre para mover la posición de la herramienta.\n4. Ajustar herramientas: Haga doble clic para mostrar los puntos de control para rotar, redimensionar y eliminar.\n5. Dibujo en bordes: Dibujar cerca de los bordes de la herramienta ajustará el trazo al borde.\n6. Instancias múltiples: Puede colocar múltiples herramientas en el lienzo simultáneamente.",
            timeDisplay: "Guía de configuración de visualización de hora:\n1. Opciones de visualización: Elija mostrar fecha, hora o ambas.\n2. Zona horaria: Soporta las principales zonas horarias globales con ajuste automático de horario de verano.\n3. Formato: Formato de hora 12/24 horas, múltiples formatos de fecha disponibles.\n4. Estilo: Personalice el color de fuente, color de fondo y opacidad.\n5. Modo de pantalla completa: Clic simple o doble clic para entrar en la visualización de hora en pantalla completa.\n6. Arrastrar para mover: El widget de visualización de hora se puede arrastrar libremente a cualquier posición.",
            insertImage: "**Insertar imagen**:\n1. Seleccione una imagen local para insertarla en el lienzo.\n2. Arrastre para mover después de insertar.\n3. Use los controladores para escalar y rotar.\n4. Soporta volteo horizontal y vertical.",
            insertText: "**Insertar texto**:\n1. Escriba texto en la ventana emergente (admite varias líneas).\n2. Ajuste tamaño y color.\n3. Mueva, rote y escale el cuadro de texto.\n4. Haga doble clic para editar de nuevo."
        }
    },
    common: {
        help: "Ayuda"
    }
};
