window.help_translations = {
    help: {
        tools: {
            pen: "Guide de l'outil Stylo :\n1. Types de stylo : Normal, Crayon (granuleux), Stylo bille (pression), Plume (calligraphie), ou Pinceau (encre).\n2. Couleur : 8 préréglages disponibles. Cliquez sur l'icône plus pour un sélecteur de couleur personnalisé.\n3. Taille : Ajustez la largeur du trait (1-50px) avec le curseur.\n4. Astuce : Maintenez la touche Shift pour tracer des lignes droites.",
            shape: "Guide de l'outil Forme :\n1. Formes : Ligne, Rectangle, Cercle, Ellipse, Flèche, Double flèche.\n2. Comment dessiner : Appuyez et faites glisser, puis relâchez pour terminer.\n3. Taille de la flèche : Ajustez la taille de la pointe de flèche indépendamment (limitée à au moins l'épaisseur de la ligne).\n4. Style : Les formes utilisent les paramètres de couleur et d'épaisseur actuels du stylo.",
            eraser: "Guide de l'outil Gomme :\n1. Forme : Choisissez entre une gomme circulaire ou carrée.\n2. Taille : Ajustez la taille de la gomme avec le curseur.\n3. Tout effacer : Utilisez le bouton 'Effacer' de la barre d'outils pour effacer tout le canevas.",
            select: "Guide de l'outil Sélection :\n1. Mode clic : Touchez un tracé ou un objet existant pour le sélectionner.\n2. Sélection rectangulaire : Faites glisser un cadre pour sélectionner tout ce qu'il contient.\n3. Lasso : Dessinez un contour libre pour les zones irrégulières.\n4. Astuce : Après la sélection, utilisez les poignées ou les actions pour déplacer, copier ou supprimer.",
            lineStyle: "Guide du style de ligne :\n1. Styles : Passez de plein à pointillé, tireté, ondulé ou multiligne.\n2. Densité : Les styles tireté, pointillé et ondulé disposent de réglages dédiés.\n3. Multiligne : Ajustez séparément le nombre de lignes et leur espacement.\n4. Aperçu : Vérifiez l'échantillon avant d'appliquer pour garder un rendu cohérent entre stylo et formes."
        },
        settings: "Guide des paramètres :\n1. Onglets : Général, Affichage, Canevas, Arrière-plan, À propos, Annonces et Plus sont organisés par usage.\n2. Aperçu en direct : La plupart des options s'appliquent immédiatement pendant l'utilisation du tableau.\n3. Langue : Changer de langue met à jour l'interface et l'aide sans rechargement.\n4. Astuce : S'il y a beaucoup d'options, ouvrez d'abord l'onglet concerné puis ajustez seulement cette section.",
        background: "Guide des paramètres d'arrière-plan :\n1. Couleur : Choisissez la couleur d'arrière-plan du canevas.\n2. Motifs : Grilles, Lignes, Portée musicale, Système de coordonnées, etc.\n3. Image : Téléchargez une image locale comme arrière-plan. Prend en charge le déplacement, le redimensionnement, la rotation et le retournement.\n4. Coordonnées : Lorsque le motif Coordonnées est sélectionné, cliquez sur 'Déplacer l'origine' pour faire glisser le point d'origine sur le canevas.",
        features: {
            shape: "**Outil Forme dans Plus de fonctionnalités** :\n1. Cliquez pour passer au mode dessin de formes.\n2. Utilise la couleur et l'épaisseur actuelles du trait.\n3. Prend en charge ligne, rectangle, cercle, ellipse, flèche et double flèche.",
            timer: "Guide du Minuteur :\n1. Modes : Chronomètre et Compte à rebours.\n2. Réglage du temps : Entrez les heures, minutes et secondes pour le compte à rebours.\n3. Son : Activez le son de fin. Prend en charge le téléchargement audio personnalisé.\n4. Boucle : Définissez le nombre de répétitions du son.\n5. Plein écran : Affichez le minuteur en mode plein écran.\n6. Mode minimal : Double-cliquez sur l'affichage du temps pour basculer vers la vue minimale.",
            randomPicker: "Guide du Sélecteur aléatoire :\n1. Importer des noms :\n   - Manuel : Tapez les noms, un par ligne.\n   - Import Excel : Cliquez sur 'Importer' dans les paramètres, sélectionnez un fichier Excel/CSV. Lecture automatique de la colonne 'Nom' (personnalisable).\n2. Modes : Sélection par Nom ou Numéro.\n3. Répétition : Activez 'Autoriser les répétitions' pour permettre de sélectionner le même nom plusieurs fois.",
            scoreboard: "Guide du Tableau de scores :\n1. Ajouter une équipe : Cliquez pour ajouter une nouvelle colonne de score.\n2. Ajuster le score : Cliquez sur les boutons '+' ou '-'.\n3. Modifier le nom : Double-cliquez sur le nom de l'équipe pour le modifier.\n4. Réinitialiser : Remet tous les scores à zéro mais conserve les équipes.",
            teachingTools: "Guide des Outils pédagogiques :\n1. Types d'outils : Règle (2 styles) et Équerre (types 60° et 45°).\n2. Ajouter des outils : Définissez la quantité dans la section 'Ajouter nouveau' et cliquez sur 'Confirmer' pour ajouter au canevas.\n3. Déplacer les outils : Simple-cliquez et faites glisser pour déplacer la position de l'outil.\n4. Ajuster les outils : Double-cliquez pour afficher les points de contrôle pour la rotation, le redimensionnement et la suppression.\n5. Dessin sur les bords : Le dessin près des bords de l'outil accrochera le trait au bord.\n6. Instances multiples : Vous pouvez placer plusieurs outils sur le canevas simultanément.",
            timeDisplay: "Guide des Paramètres d'affichage de l'heure :\n1. Options d'affichage : Choisissez d'afficher la date, l'heure ou les deux.\n2. Fuseau horaire : Prend en charge les principaux fuseaux horaires mondiaux avec ajustement automatique de l'heure d'été.\n3. Format : Format horaire 12/24 heures, plusieurs formats de date disponibles.\n4. Style : Personnalisez la couleur de la police, la couleur d'arrière-plan et l'opacité.\n5. Mode plein écran : Simple-clic ou double-clic pour entrer en affichage plein écran de l'heure.\n6. Glisser pour déplacer : Le widget d'affichage de l'heure peut être librement déplacé à n'importe quelle position.",
            insertImage: "**Insérer une image** :\n1. Sélectionnez une image locale à insérer sur le canevas.\n2. Faites glisser pour déplacer après insertion.\n3. Utilisez les poignées pour redimensionner et faire pivoter.\n4. Le retournement horizontal/vertical est pris en charge.",
            insertText: "**Insérer du texte** :\n1. Saisissez le texte dans la fenêtre contextuelle (multiligne pris en charge).\n2. Ajustez taille et couleur.\n3. Déplacez, faites pivoter et redimensionnez la zone de texte.\n4. Double-cliquez pour rééditer."
        }
    },
    common: {
        help: "Aide"
    }
};
